### ISSUE TITLE
ERR_INVALID_ARG_TYPE error for Node v10.5.0

### ISSUE THREAD

**Issue by arianseyedi** [darkguy2008/parallelshell#67]
Hello,

I am trying to test parallelshell (package.json at the bottom of this issue for ref) simply running echo commands, but I get the following: 

> confusion@1.0.0 echo1echo2 C:\Users\Public\r\b\c
**> parallelshell "echo 1" "echo 2"**

child_process.js:420
    throw new ERR_INVALID_ARG_TYPE('options.cwd', 'string', options.cwd);
    ^

**TypeError [ERR_INVALID_ARG_TYPE]: The "options.cwd" property must be of type string.** Received type function
    at normalizeSpawnArguments (child_process.js:420:11)
    at spawn (child_process.js:522:38)
    at C:\Users\Public\repos\Bootstrap4\conFusion\node_modules\parallelshell\index.js:104:17
    at Array.forEach (<anonymous>)
    at Object.<anonymous> (C:\Users\Public\r\b\c\node_modules\parallelshell\index.js:100:6)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
**npm ERR! confusion@1.0.0 echo1echo2: `parallelshell "echo 1" "echo 2"`**
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the confusion@1.0.0 echo1echo2 script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\username\appdata\Roaming\npm-cache\_logs\2018-06-27T08_21_16_022Z-debug.log

The package I have installed in my project folder has the following package.json file:

{
  "_from": "parallelshell",
  "_id": "parallelshell@3.0.2",
  "_inBundle": false,
  "_integrity": "sha512-aW73W8tmYiFZtQi41pweV3WWT6o/EvSxAVQHbumOhN53H47OuWQwrRc11xQ2i44GFvR5AjtzhD92r8Kv9X+7Iw==",
  "_location": "/parallelshell",
  "_phantomChildren": {},
  "_requested": {
    "type": "tag",
    "registry": true,
    "raw": "parallelshell",
    "name": "parallelshell",
    "escapedName": "parallelshell",
    "rawSpec": "",
    "saveSpec": null,
    "fetchSpec": "latest"
  },
  "_requiredBy": [
    "#DEV:/",
    "#USER"
  ],
  "_resolved": "https://registry.npmjs.org/parallelshell/-/parallelshell-3.0.2.tgz",
  "_shasum": "fffc55aaa145bdd44b5381cf7fd5e521fc21aa7b",
  "_spec": "parallelshell",
  "_where": "C:\\Users\\Public\\repos\\Bootstrap4\\conFusion",
  "author": {
    "name": "DARKGuy",
    "email": "darkguy2008@gmail.com"
  },
  "bin": {
    "parallelshell": "./index.js"
  },
  "bugs": {
    "url": "https://github.com/darkguy2008/parallelshell/issues"
  },
  "bundleDependencies": false,
  "deprecated": false,
  "description": "Invoke multiple commands, running in parallel",
  "devDependencies": {
    "bluebird": "^3.5.0",
    "chai": "^4.0.2",
    "coffee-script": "^1.12.6",
    "mocha": "^3.4.2"
  },
  "homepage": "https://github.com/darkguy2008/parallelshell",
  "keywords": [
    "parallel",
    "shell"
  ],
  "license": "MIT",
  "main": "index.js",
  "name": "parallelshell",
  "repository": {
    "type": "git",
    "url": "git+ssh://git@github.com/darkguy2008/parallelshell.git"
  },
  "scripts": {
    "test": "mocha"
  },
  "version": "3.0.2"
}

Thank you so much. Sorry if I was all over the place or something. I'm new to this.

Arian

**Comment by alexander-schranz** [comment]
@arianseyedi think this is related to this issue: https://github.com/darkguy2008/parallelshell/issues/64 which I think is fixed but not released. ping @darkguy2008

**Comment by alexander-schranz** [comment]
@tfritsch-km I currently switch to [concurrently](https://github.com/kimmobrunfeldt/concurrently) as this repo seems to be unmaintained. There was also some discussion from the old maintainer of parallelshell to merge all this task/parallel script repo's in one see https://github.com/mysticatea/npm-run-all/issues/10 so there is a list of alternatives.

**Comment by abhijithchowdary2** [comment]
Have we got solution for the error of parallelshell??

**Comment by alexander-schranz** [comment]
@abhijithchowdary2 this package is I think not longer maintained as you see last release 2017. I would switch to alternative. As written above I did switch to concurrently which seems still be maintained: https://github.com/kimmobrunfeldt/concurrently

**Comment by abhijithchowdary2** [comment]
Thank you for the suggestion : )
