### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by jatintuteja** [darkguy2008/parallelshell#74]
Error: spawn cmd ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:252:12)
    at onErrorNT (internal/child_process.js:427:16)
    [... lines matching original stack trace ...]
    at internal/main/run_main_module.js:21:11
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! confusion@1.0.0 watch:all: `parallelshell "npm run watch:scss" "npm run lite"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the confusion@1.0.0 watch:all script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-05-08T14_50_07_742Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! confusion@1.0.0 start: `npm run watch:all`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the confusion@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\user\AppData\Roaming\npm-cache\_logs\2020-05-08T14_50_08_063Z-debug.log

**Comment by Sailokeshg** [comment]
Even i got the exact error.How to solve this.Can anyone help me to go through it

**Comment by HediMuhamad** [comment]
1. Open this javascript file -> node_modules\parallelshell\index.js
2. Goto -> line: 105
3. Replace it with -> cwd: process.versions.node < **8.0** ? process.cwd : process.cwd(),

Note: I've been using this solution for 3 months and haven't had any other issue, even the solution source is not the developer.
